=== kpopdb/kpopdb/idol.schema.json
{
    "$id": "https://github.com/kpopdb/kpopdb/blob/master/idol.schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "required": [
      "givenName",
      "givenNameRoman",
      "givenNameKorean",
      "givenNameKoreanRoman",
      "familyName",
      "familyNameRoman",
      "stageNameHangul",
      "stageNameRoman",
      "birthday",
      "nationality",
      "status",
      "sex"
    ],
    "title": "Idol",
    "type": "object",
    "properties": {
        "givenName": {
            "description": "Given (first) name in native language",
            "type": "string"
        },
        "givenNameRoman": {
            "description": "Given (first) name romanized",
            "type": "string"
        },
        "givenNameKorean": {
            "description": "Korean given (first) name",
            "type": "string"
        },
        "givenNameKoreanRoman": {
            "description": "Korean given (first) name romanized",
            "type": "string"
        },
        "familyName": {
            "description": "Family (last) name",
            "type": "string"
        },
        "familyNameRoman": {
            "description": "Family (last) name Romanzied",
            "type": "string"
        },
        "familyNameKorean": {
            "description": "Korean family (last) name in Hangul",
            "type": "string"
        },
        "familyNameKoreanRoman": {
            "description": "Korean family (last) name in Hangul",
            "type": "string"
        },
        "stageNameHangul": {
            "description": "Stage (last) name in Hangul",
            "type": "string"
        },
        "stageNameRoman": {
            "description": "Stage (last) name Romanzied",
            "type": "string"
        },
        "birthday": {
            "description": "Birthday",
            "type": "string",
            "format": "date"
        },
        "sex": {
            "description": "Idol's sex",
            "enum": ["male", "female"]
        },
        "nationality": {
            "description": "Nationality",
            "enum": ["korean", "chinese", "thai", "korean-american"]
        },
        "groupHangul": {
            "description": "Group name in Hangul",
            "type": "string"
        },
        "groupRoman": {
            "description": "Group name Romanized",
          "type": "string"
        },
        "solo": {
            "description": "Is the idol a solo performer?",
          "type": "boolean"
        },
        "soloDebutDate": {
            "description": "Solo Debut Date",
            "type": "string",
            "format": "date"
        },
        "status": {
            "description": "Idol's activity status",
            "enum": ["active", "inactive", "former"]
        }
    }
}

=== kpopdb/kpopdb/gg/fromis_9/gyuri.idol.json
{
    "givenName": "규리",
    "givenNameRoman": "Gyuri",
    "givenNameKorean": "규리",
    "givenNameKoreanRoman": "Gyuri",
    "familyName": "장",
    "familyNameRoman": "Jang",
    "familyNameKorean": "장",
    "familyNameKoreanRoman": "Jang",
    "stageNameHangul": "규리",
    "stageNameRoman": "Gyuri",
    "birthday": "1997-12-27",
    "sex": "female",
    "nationality": "korean",
    "groupHangul": "프로미스나인",
    "groupRoman": "fromis_9",
    "status": "active"
}

=== kpopdb/kpopdb/gg/dreamcatcher/siyeon.idol.json
{
    "givenName": "시연",
    "givenNameRoman": "Siyeon",
    "givenNameKorean": "시연",
    "givenNameKoreanRoman": "Siyeon",
    "familyName": "이",
    "familyNameRoman": "Lee",
    "familyNameKorean": "이",
    "familyNameKoreanRoman": "Lee",
    "stageNameHangul": "시연",
    "stageNameRoman": "Siyeon",
    "birthday": "1995-10-01",
    "sex": "female",
    "nationality": "korean",
    "groupHangul": "드림캐쳐",
    "groupRoman": "Dreamcatcher",
    "status": "active"
}

=== kpopdb/kpopdb/gg/oh_my_girl/yooa.idol.json
{
    "givenName": "시아",
    "givenNameRoman": "Shiah",
    "givenNameKorean": "시아",
    "givenNameKoreanRoman": "Shiah",
    "familyName": "유",
    "familyNameRoman": "Yoo",
    "familyNameKorean": "유",
    "familyNameKoreanRoman": "Yoo",
    "stageNameHangul": "유아",
    "stageNameRoman": "YooA",
    "birthday": "1995-09-17",
    "sex": "female",
    "nationality": "korean",
    "groupHangul": "오마이걸",
    "groupRoman": "OH MY GIRL",
    "status": "active"
}

=== kpopdb/kpopdb/gg/dreamcatcher/gahyeon.idol.json
{
    "givenName": "가현",
    "givenNameRoman": "Gahyeon",
    "givenNameKorean": "가현",
    "givenNameKoreanRoman": "Gahyeon",
    "familyName": "이",
    "familyNameRoman": "Lee",
    "familyNameKorean": "이",
    "familyNameKoreanRoman": "Lee",
    "stageNameHangul": "가현",
    "stageNameRoman": "Gahyeon",
    "birthday": "1999-02-03",
    "sex": "female",
    "nationality": "korean",
    "groupHangul": "드림캐쳐",
    "groupRoman": "Dreamcatcher",
    "status": "active"
}

=== kpopdb/kpopdb/solo/jessica.idol.json
{
    "givenName": "Jessica",
    "givenNameRoman": "Jessica",
    "givenNameKorean": "수연",
    "givenNameKoreanRoman": "Sooyeon",
    "familyName": "정",
    "familyNameRoman": "Jung",
    "familyNameKorean": "정",
    "familyNameKoreanRoman": "Jung",
    "stageNameHangul": "태연",
    "stageNameRoman": "Jessica",
    "birthday": "1989-04-18",
    "sex": "female",
    "nationality": "korean-american",
    "solo": true,
    "soloDebutDate": "2016-05-16",
    "status": "inactive"
}

=== kpopdb/kpopdb/gg/dreamcatcher/dami.idol.json
{
    "givenName": "유빈",
    "givenNameRoman": "Yubin",
    "givenNameKorean": "유빈",
    "givenNameKoreanRoman": "Yubin",
    "familyName": "이",
    "familyNameRoman": "Lee",
    "familyNameKorean": "이",
    "familyNameKoreanRoman": "Lee",
    "stageNameHangul": "다미",
    "stageNameRoman": "Dami",
    "birthday": "1997-03-07",
    "sex": "female",
    "nationality": "korean",
    "groupHangul": "드림캐쳐",
    "groupRoman": "Dreamcatcher",
    "status": "active"
}

=== kpopdb/kpopdb/bg/seventeen/wonwoo.idol.json
{
    "givenName": "원우",
    "givenNameRoman": "Wonwoo",
    "givenNameKorean": "원우",
    "givenNameKoreanRoman": "Wonwoo",
    "familyName": "전",
    "familyNameRoman": "Jeon",
    "familyNameKorean": "전",
    "familyNameKoreanRoman": "Jeon",
    "stageNameHangul": "원우",
    "stageNameRoman": "Wonwoo",
    "birthday": "1996-07-17",
    "sex": "male",
    "nationality": "korean",
    "groupHangul": "세븐틴",
    "groupRoman": "SEVENTEEN",
    "status": "active"
}

=== kpopdb/kpopdb/gg/oh_my_girl/jiho.idol.json
{
    "givenName": "지호",
    "givenNameRoman": "Jiho",
    "givenNameKorean": "지호",
    "givenNameKoreanRoman": "Jiho",
    "familyName": "김",
    "familyNameRoman": "Kim",
    "familyNameKorean": "김",
    "familyNameKoreanRoman": "Kim",
    "stageNameHangul": "지호",
    "stageNameRoman": "Jiho",
    "birthday": "1997-04-04",
    "sex": "female",
    "nationality": "korean",
    "groupHangul": "오마이걸",
    "groupRoman": "OH MY GIRL",
    "status": "active"
}
