=== kpopdb/kpopdb/idol.schema.json
{
    "$id": "https://github.com/kpopdb/kpopdb/blob/master/idol.schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "required": [
      "givenName",
      "givenNameRoman",
      "givenNameKorean",
      "givenNameKoreanRoman",
      "familyName",
      "familyNameRoman",
      "stageNameHangul",
      "stageNameRoman",
      "birthday",
      "nationality",
      "status",
      "sex"
    ],
    "title": "Idol",
    "type": "object",
    "properties": {
        "givenName": {
            "description": "Given (first) name in native language",
            "type": "string"
        },
        "givenNameRoman": {
            "description": "Given (first) name romanized",
            "type": "string"
        },
        "givenNameKorean": {
            "description": "Korean given (first) name",
            "type": "string"
        },
        "givenNameKoreanRoman": {
            "description": "Korean given (first) name romanized",
            "type": "string"
        },
        "familyName": {
            "description": "Family (last) name",
            "type": "string"
        },
        "familyNameRoman": {
            "description": "Family (last) name Romanzied",
            "type": "string"
        },
        "familyNameKorean": {
            "description": "Korean family (last) name in Hangul",
            "type": "string"
        },
        "familyNameKoreanRoman": {
            "description": "Korean family (last) name in Hangul",
            "type": "string"
        },
        "stageNameHangul": {
            "description": "Stage (last) name in Hangul",
            "type": "string"
        },
        "stageNameRoman": {
            "description": "Stage (last) name Romanzied",
            "type": "string"
        },
        "birthday": {
            "description": "Birthday",
            "type": "string",
            "format": "date"
        },
        "sex": {
            "description": "Idol's sex",
            "enum": ["male", "female"]
        },
        "nationality": {
            "description": "Nationality",
            "enum": ["korean", "chinese", "thai", "korean-american"]
        },
        "groupHangul": {
            "description": "Group name in Hangul",
            "type": "string"
        },
        "groupRoman": {
            "description": "Group name Romanized",
          "type": "string"
        },
        "solo": {
            "description": "Is the idol a solo performer?",
          "type": "boolean"
        },
        "soloDebutDate": {
            "description": "Solo Debut Date",
            "type": "string",
            "format": "date"
        },
        "status": {
            "description": "Idol's activity status",
            "enum": ["active", "inactive", "former"]
        }
    }
}

=== kpopdb/kpopdb/bg/seventeen/joshua.idol.json
{
    "givenName": "Joshua",
    "givenNameRoman": "Joshua",
    "givenNameKorean": "지수",
    "givenNameKoreanRoman": "Jisoo",
    "familyName": "홍",
    "familyNameRoman": "Hong",
    "familyNameKorean": "홍",
    "familyNameKoreanRoman": "Hong",
    "stageNameHangul": "조슈아",
    "stageNameRoman": "Joshua",
    "birthday": "1995-12-30",
    "sex": "male",
    "nationality": "korean-american",
    "groupHangul": "세븐틴",
    "groupRoman": "SEVENTEEN",
    "status": "active"
}

=== kpopdb/kpopdb/gg/oh_my_girl/mimi.idol.json
{
    "givenName": "미현",
    "givenNameRoman": "Mihyun",
    "givenNameKorean": "미현",
    "givenNameKoreanRoman": "Mihyun",
    "familyName": "김",
    "familyNameRoman": "Kim",
    "familyNameKorean": "김",
    "familyNameKoreanRoman": "Kim",
    "stageNameHangul": "미미",
    "stageNameRoman": "Mimi",
    "birthday": "1995-05-01",
    "sex": "female",
    "nationality": "korean",
    "groupHangul": "오마이걸",
    "groupRoman": "OH MY GIRL",
    "status": "active"
}

=== kpopdb/kpopdb/bg/seventeen/scoups.idol.json
{
    "givenName": "승철",
    "givenNameRoman": "Seungcheol",
    "givenNameKorean": "승철",
    "givenNameKoreanRoman": "Seungcheol",
    "familyName": "최",
    "familyNameRoman": "Choi",
    "familyNameKorean": "최",
    "familyNameKoreanRoman": "Choi",
    "stageNameHangul": "에스쿱스",
    "stageNameRoman": "S.Coups",
    "birthday": "1995-08-08",
    "sex": "male",
    "nationality": "korean",
    "groupHangul": "세븐틴",
    "groupRoman": "SEVENTEEN",
    "status": "active"
}

=== kpopdb/kpopdb/gg/fromis_9/jisun.idol.json
{
    "givenName": "지선",
    "givenNameRoman": "Jisun",
    "givenNameKorean": "지선",
    "givenNameKoreanRoman": "Jisun",
    "familyName": "노",
    "familyNameRoman": "Roh",
    "familyNameKorean": "노",
    "familyNameKoreanRoman": "Roh",
    "stageNameHangul": "지선",
    "stageNameRoman": "Jisun",
    "birthday": "1998-11-23",
    "sex": "female",
    "nationality": "korean",
    "groupHangul": "프로미스나인",
    "groupRoman": "fromis_9",
    "status": "active"
}

=== kpopdb/kpopdb/gg/fromis_9/chaeyoung.idol.json
{
    "givenName": "채영",
    "givenNameRoman": "Chaeyoung",
    "givenNameKorean": "채영",
    "givenNameKoreanRoman": "Chaeyoung",
    "familyName": "이",
    "familyNameRoman": "Lee",
    "familyNameKorean": "이",
    "familyNameKoreanRoman": "Lee",
    "stageNameHangul": "채영",
    "stageNameRoman": "Chaeyoung",
    "birthday": "2000-05-14",
    "sex": "female",
    "nationality": "korean",
    "groupHangul": "프로미스나인",
    "groupRoman": "fromis_9",
    "status": "active"
}

=== kpopdb/kpopdb/gg/dreamcatcher/jiu.idol.json
{
    "givenName": "민지",
    "givenNameRoman": "Minji",
    "givenNameKorean": "민지",
    "givenNameKoreanRoman": "Minji",
    "familyName": "김",
    "familyNameRoman": "Kim",
    "familyNameKorean": "김",
    "familyNameKoreanRoman": "Kim",
    "stageNameHangul": "지유",
    "stageNameRoman": "JiU",
    "birthday": "1994-05-17",
    "sex": "female",
    "nationality": "korean",
    "groupHangul": "드림캐쳐",
    "groupRoman": "Dreamcatcher",
    "status": "active"
}

=== kpopdb/kpopdb/gg/oh_my_girl/arin.idol.json
{
    "givenName": "예원",
    "givenNameRoman": "Yewon",
    "givenNameKorean": "예원",
    "givenNameKoreanRoman": "Yewon",
    "familyName": "최",
    "familyNameRoman": "Choi",
    "familyNameKorean": "최",
    "familyNameKoreanRoman": "Choi",
    "stageNameHangul": "아린",
    "stageNameRoman": "Arin",
    "birthday": "1999-06-18",
    "sex": "female",
    "nationality": "korean",
    "groupHangul": "오마이걸",
    "groupRoman": "OH MY GIRL",
    "status": "active"
}

=== kpopdb/kpopdb/gg/dreamcatcher/yoohyeon.idol.json
{
    "givenName": "유현",
    "givenNameRoman": "Yoohyeon",
    "givenNameKorean": "유현",
    "givenNameKoreanRoman": "Yoohyeon",
    "familyName": "김",
    "familyNameRoman": "Kim",
    "familyNameKorean": "김",
    "familyNameKoreanRoman": "Kim",
    "stageNameHangul": "유현",
    "stageNameRoman": "Yoohyeon",
    "birthday": "1997-01-07",
    "sex": "female",
    "nationality": "korean",
    "groupHangul": "드림캐쳐",
    "groupRoman": "Dreamcatcher",
    "status": "active"
}
