=== kpopdb/kpopdb/idol.schema.json
{
    "$id": "https://github.com/kpopdb/kpopdb/blob/master/idol.schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "required": [
      "givenName",
      "givenNameRoman",
      "givenNameKorean",
      "givenNameKoreanRoman",
      "familyName",
      "familyNameRoman",
      "stageNameHangul",
      "stageNameRoman",
      "birthday",
      "nationality",
      "status",
      "sex"
    ],
    "title": "Idol",
    "type": "object",
    "properties": {
        "givenName": {
            "description": "Given (first) name in native language",
            "type": "string"
        },
        "givenNameRoman": {
            "description": "Given (first) name romanized",
            "type": "string"
        },
        "givenNameKorean": {
            "description": "Korean given (first) name",
            "type": "string"
        },
        "givenNameKoreanRoman": {
            "description": "Korean given (first) name romanized",
            "type": "string"
        },
        "familyName": {
            "description": "Family (last) name",
            "type": "string"
        },
        "familyNameRoman": {
            "description": "Family (last) name Romanzied",
            "type": "string"
        },
        "familyNameKorean": {
            "description": "Korean family (last) name in Hangul",
            "type": "string"
        },
        "familyNameKoreanRoman": {
            "description": "Korean family (last) name in Hangul",
            "type": "string"
        },
        "stageNameHangul": {
            "description": "Stage (last) name in Hangul",
            "type": "string"
        },
        "stageNameRoman": {
            "description": "Stage (last) name Romanzied",
            "type": "string"
        },
        "birthday": {
            "description": "Birthday",
            "type": "string",
            "format": "date"
        },
        "sex": {
            "description": "Idol's sex",
            "enum": ["male", "female"]
        },
        "nationality": {
            "description": "Nationality",
            "enum": ["korean", "chinese", "thai", "korean-american"]
        },
        "groupHangul": {
            "description": "Group name in Hangul",
            "type": "string"
        },
        "groupRoman": {
            "description": "Group name Romanized",
          "type": "string"
        },
        "solo": {
            "description": "Is the idol a solo performer?",
          "type": "boolean"
        },
        "soloDebutDate": {
            "description": "Solo Debut Date",
            "type": "string",
            "format": "date"
        },
        "status": {
            "description": "Idol's activity status",
            "enum": ["active", "inactive", "former"]
        }
    }
}

=== kpopdb/kpopdb/gg/girls_generation/seohyun.idol.json
{
    "givenName": "주현",
    "givenNameRoman": "Joohyun",
    "givenNameKorean": "주현",
    "givenNameKoreanRoman": "Joohyun",
    "familyName": "서",
    "familyNameRoman": "Seo",
    "familyNameKorean": "서",
    "familyNameKoreanRoman": "Seo",
    "stageNameHangul": "서현",
    "stageNameRoman": "Seohyun",
    "birthday": "1991-06-28",
    "sex": "female",
    "nationality": "korean",
    "groupHangul": "소녀시대",
    "groupRoman": "Girls' Generation",
    "status": "active"
}

=== kpopdb/kpopdb/gg/girls_generation/sooyoung.idol.json
{
    "givenName": "수영",
    "givenNameRoman": "Sooyoung",
    "givenNameKorean": "수영",
    "givenNameKoreanRoman": "Sooyoung",
    "familyName": "최",
    "familyNameRoman": "Choi",
    "familyNameKorean": "최",
    "familyNameKoreanRoman": "Choi",
    "stageNameHangul": "수영",
    "stageNameRoman": "Sooyoung",
    "birthday": "1989-03-09",
    "sex": "female",
    "nationality": "korean",
    "groupHangul": "소녀시대",
    "groupRoman": "Girls' Generation",
    "status": "active"
}

=== kpopdb/kpopdb/bg/seventeen/dino.idol.json
{
    "givenName": "찬",
    "givenNameRoman": "Chan",
    "givenNameKorean": "찬",
    "givenNameKoreanRoman": "Chan",
    "familyName": "이",
    "familyNameRoman": "Lee",
    "familyNameKorean": "이",
    "familyNameKoreanRoman": "Lee",
    "stageNameHangul": "디노",
    "stageNameRoman": "Dino",
    "birthday": "1999-02-11",
    "sex": "male",
    "nationality": "korean",
    "groupHangul": "세븐틴",
    "groupRoman": "SEVENTEEN",
    "status": "active"
}

=== kpopdb/kpopdb/bg/seventeen/hoshi.idol.json
{
    "givenName": "순영",
    "givenNameRoman": "Soonyoung",
    "givenNameKorean": "순영",
    "givenNameKoreanRoman": "Soonyoung",
    "familyName": "권",
    "familyNameRoman": "Kwon",
    "familyNameKorean": "권",
    "familyNameKoreanRoman": "Kwon",
    "stageNameHangul": "호시",
    "stageNameRoman": "Hoshi",
    "birthday": "1996-06-15",
    "sex": "male",
    "nationality": "korean",
    "groupHangul": "세븐틴",
    "groupRoman": "SEVENTEEN",
    "status": "active"
}

=== kpopdb/kpopdb/bg/seventeen/vernon.idol.json
{
    "givenName": "Hansol",
    "givenNameRoman": "Hansol",
    "givenNameKorean": "한솔",
    "givenNameKoreanRoman": "Hansol",
    "familyName": "Chwe",
    "familyNameRoman": "Chwe",
    "familyNameKorean": "최",
    "familyNameKoreanRoman": "Choi",
    "stageNameHangul": "버논",
    "stageNameRoman": "Vernon",
    "birthday": "1998-02-18",
    "sex": "male",
    "nationality": "korean-american",
    "groupHangul": "세븐틴",
    "groupRoman": "SEVENTEEN",
    "status": "active"
}

=== kpopdb/kpopdb/bg/seventeen/seungkwan.idol.json
{
    "givenName": "승관",
    "givenNameRoman": "Seungkwan",
    "givenNameKorean": "승관",
    "givenNameKoreanRoman": "Seungkwan",
    "familyName": "부",
    "familyNameRoman": "Boo",
    "familyNameKorean": "부",
    "familyNameKoreanRoman": "Boo",
    "stageNameHangul": "승관",
    "stageNameRoman": "Seungkwan",
    "birthday": "1998-01-06",
    "sex": "male",
    "nationality": "korean",
    "groupHangul": "세븐틴",
    "groupRoman": "SEVENTEEN",
    "status": "active"
}

=== kpopdb/kpopdb/gg/fromis_9/jiwon.idol.json
{
    "givenName": "지원",
    "givenNameRoman": "Jiwon",
    "givenNameKorean": "지원",
    "givenNameKoreanRoman": "Jiwon",
    "familyName": "박",
    "familyNameRoman": "Park",
    "familyNameKorean": "박",
    "familyNameKoreanRoman": "Park",
    "stageNameHangul": "지원",
    "stageNameRoman": "Jiwon",
    "birthday": "1998-03-20",
    "sex": "female",
    "nationality": "korean",
    "groupHangul": "프로미스나인",
    "groupRoman": "fromis_9",
    "status": "active"
}

=== kpopdb/kpopdb/gg/fromis_9/jiheon.idol.json
{
    "givenName": "지헌",
    "givenNameRoman": "Jiheon",
    "givenNameKorean": "지헌",
    "givenNameKoreanRoman": "Jiheon",
    "familyName": "백",
    "familyNameRoman": "Baek",
    "familyNameKorean": "백",
    "familyNameKoreanRoman": "Baek",
    "stageNameHangul": "지헌",
    "stageNameRoman": "Jiheon",
    "birthday": "2003-04-17",
    "sex": "female",
    "nationality": "korean",
    "groupHangul": "프로미스나인",
    "groupRoman": "fromis_9",
    "status": "active"
}
